lunguage: ruby
rvm: 
  - 2.4.5
notifications:
  email: false

addons:
  postgresql: '11.7'

  
bundler_args: --without development --deployment --jobs=3 --retry=3
cache: bundler

before_script:
  - bundle update --bundler
  - psql -c 'create database th_demo_test;' -U postgres
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - bundle exec rake db:setup

gemfile:
  - Gemfile
  
